apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service-container
        image: 003866745935.dkr.ecr.ap-southeast-1.amazonaws.com/reynaldiekoz:go-service
        imagePullPolicy: Always
        ports:
        - containerPort: 6011
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6011
      nodePort: 30611

